#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,         sensorAnalogActive)
#pragma config(Sensor, S3,     ANGLE_SENSOR,   sensorI2CCustom)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right_motor,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     left_motor,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
*
*  @file auto.c
*
*  @brief The automatic program for the robot.
*
*  @copyright Copyright 2013, Got Robot? FTC Team 5037
*
*/

/*Includes*/

#include "../src/lib/abs_global.h"
#include "../src/lib/abs_turn.h"
#include "../src/lib/math_utils.h"
#include "../src/lib/abs_gyro_cal.h"
//#include "JoystickDriver.c"
#include "../src/lib/abs_create_mem.h"
#include "../src/lib/abs_initialize_system.h"
#include "../src/lib/abs_drive.h"

//========================================
// Main program
//========================================

task main()
{
	//waitforstart();
  abs_initialize_system();
  abs_drive(FORWARD, E_DISTANCE, 52, 50);
  //abs_turn(COUNTERCLOCKWISE, SWING, 360, 50);
  //abs_drive(BACKWARD, E_TIME, 360, 50);
  //abs_turn(CLOCKWISE, POINT, 360, 50);
  wait1Msec(5000);        // this is a hack because the last command isnt running because the program is ending as soon as it is run
}
