#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     IR2,            sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     right_motor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left_motor,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"

int speed = 75;
int time = 2000;

int IR = 0;
int IR_adv = 0;
int IR_count = 0;
int IR_final = 0;
int IR_datalog[7];

task main()
{
	memset(IR_datalog,0,7);
	//StartTask(display);
	//waitForStart();

	motor[right_motor] = speed;
	motor[left_motor] = speed;
	for(int i=0;i<6;i++)
	{
	time1[T1]= 0;
		while(time1[T1]<(time/6))
		{
			nxtDisplayBigTextLine(2,"%2d",IR);
			nxtDisplayBigTextLine(4,"%2d",IR_final);

			IR = HTIRS2readACDir(IR2);

			IR_count++;
			IR_adv = IR_adv + IR;
			IR_final = IR_adv/IR_count;

			IR_datalog[i] = IR;

			wait1Msec(10);
		}
	}

	motor[right_motor] = 0;
	motor[left_motor] = 0;

	while(true)
	{
		IR = HTIRS2readACDir(IR2);

		nxtDisplayBigTextLine(1,"%2d",IR);
		nxtDisplayBigTextLine(3,"%2d",IR_final);

		nxtDisplayTextLine(5,"%1d %1d %1d %1d %1d %1d",IR_datalog[1],IR_datalog[2],IR_datalog[3],IR_datalog[4],IR_datalog[5],IR_datalog[6]);

	//if reading 4 or 5 == 5 its 3
	//if first 3 mostly 6 position 2
	//if first 3 mostly 7 position 1

		if(IR_datalog[4]==5)nxtDisplayTextLine(6,"#3");
		else if(IR_datalog[3]<=6)nxtDisplayTextLine(6,"#2");
		else if(IR_datalog[3]==7)	nxtDisplayTextLine(6,"#1");

		else nxtDisplayTextLine(6,"error");
	}
}
