#pragma config(Sensor, S1,     EOPD_MUX,       sensorI2CCustom)
#pragma config(Sensor, S2,     leftIR,         sensorI2CCustom)
#pragma config(Sensor, S3,     rightIR,        sensorI2CCustom)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-eopd.h"
#include "drivers/hitechnic-irseeker-v2.h"

const tMUXSensor HTEOPD = msensor_S1_1;

task main()
{
	while(true)
	{
		HTEOPDsetLongRange(HTEOPD);
		nxtDisplayBigTextLine(1, "%4d", SensorValue(sonar));
		nxtDisplayBigTextLine(3, "%2d %2d",HTIRS2readACDir(leftIR),HTIRS2readACDir(rightIR));
		nxtDisplayBigTextLine(5, "%3d %3d", HTEOPDreadProcessed(HTEOPD),HTEOPDreadRaw(HTEOPD));
	}
}
