#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTSMUX,              sensorI2CCustom)
#pragma config(Sensor, S4,     COLOR,               sensorCOLORFULL)
#pragma config(Motor,  motorC,          motorC,        tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     CrateLifterMotor, tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ball_elevator, tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     left_motor,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     right_motor,   tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    ball_hoop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    right_servo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    left_servo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define bOFF 1
#define bON 2

#define mON 1
#define mOFF 2

//---------------------

int lifter_speed;

int SmokeTest;

int motors_off;

bool test_done;

bool Lifter_Pressed = false;

bool LifterH_Pressed = false;

bool oldLifterPressed = false;

bool oldLifterHPressed = false;

int Motor_Cvalue = 0;

int bearingDC = 0;
int bearingAC = 0;

//----------------------
/*
#include "drivers/HTSMUX-driver.h"
#include "drivers/LEGOTS-driver.h"

#include "JoystickDriver.c"

#include "drivers/HTMAG-driver.h"
#include "drivers/HTGYRO-driver.h"
#include "drivers/HTMC-driver.h"
#include "drivers/HTIRS2-driver.h"*/

#include "joystickdriver.c"

#include "drivers/hitechnic-sensormux.h"
#include "drivers/common.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/hitechnic-magfield.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/lego-touch.h"

//========================================
const tMUXSensor HTGYRO = msensor_S2_1;
const tMUXSensor LifterHalfStop = msensor_S2_3;
const tMUXSensor LifterEndStop = msensor_S2_2;
const tMUXSensor HTIRS2 = msensor_S2_4;

task stop_all()
{
  while(true)
  {
    switch (motors_off)
    {
    case mON:

      motor[motorC] = 0;
      motor[CrateLifterMotor] = 0;
      motor[ball_elevator] = 0;
      motor[right_motor] = 0;
      motor[left_motor] = 0;

      motors_off = mOFF;

      break;

    case mOFF:

      break;
    }
  }
}

//========================================

void beep()
{
  PlaySound(soundBlip);
  wait1Msec(350);
  PlaySound(soundBlip);
  wait1Msec(300);
  PlaySound(soundBlip);
  wait1Msec(250);
  PlaySound(soundBlip);
  wait1Msec(200);
  PlaySound(soundBlip);
  wait1Msec(150);
  PlaySound(soundBlip);
  wait1Msec(100);
  PlaySound(soundException);
  wait1Msec(250);
}

//==================================================

task smoke_test()
{
  while(true)
  {
    switch(SmokeTest)
    {

      //============================================
      // motorC test
      //============================================

    case 1:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "motorC");
      nxtDisplayBigTextLine(5, "motorC");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      while(Motor_Cvalue > -180)
      {
        motor[motorC] = -40;
      }
      motor[motorC] = 0;
      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(300);
      while(Motor_Cvalue < 0)
      {
        motor[motorC] = 40;
      }
      motor[motorC] = 0;
      wait1Msec(100);

      test_done = true;

      break;

      //============================================
      // CrateLifterMotor test
      //============================================

    case 2:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "AutoLift");
      nxtDisplayBigTextLine(5, "S1_C1_1");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      PlaySound(soundBeepBeep);
      wait1Msec(300);

      while(Lifter_Pressed == false)
      {
        motor[CrateLifterMotor] = 30;
      }
      motor[CrateLifterMotor] = 0;

      nMotorEncoder[CrateLifterMotor] = 0;

      PlaySound(soundBeepBeep);
      wait1Msec(300);

      motor[CrateLifterMotor] = -40;
      wait1Msec(800);
      motor[CrateLifterMotor] = 0;
      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(300);
      while(Lifter_Pressed == false)
      {
        motor[CrateLifterMotor] = 30;
      }
      motor[CrateLifterMotor] = 0;

      test_done = true;

      break;

      //============================================
      // move lifter
      //============================================

    case 3:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "MAN-LIFT");
      nxtDisplayBigTextLine(5, "S1_C1_1");

      motors_off =mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      while(nNxtButtonPressed == kEnterButton)
      {}

      test_done = false;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      while(nNxtButtonPressed != kEnterButton)
      {
        if(Lifter_Pressed && LifterH_Pressed != true)
        {
          if (nNxtButtonPressed == kLeftButton)
          {
            lifter_speed = -10;
          }
          if (nNxtButtonPressed == kRightButton)
          {
            lifter_speed = 70;
          }
          if(nNxtButtonPressed != kLeftButton && nNxtButtonPressed != kRightButton)
          {
            lifter_speed = 0;
          }
          motor[CrateLifterMotor] = lifter_speed;
          //===============================
        }
        else
        {
          if(Lifter_Pressed != true)
          {
            if (nNxtButtonPressed == kLeftButton)
            {
              lifter_speed = -10;
            }
          }
          if(Lifter_Pressed == true)
          {
            lifter_speed = 0;
          }
          if (nNxtButtonPressed == kRightButton)
          {
            lifter_speed = 70;
          }
          if(nNxtButtonPressed != kLeftButton && nNxtButtonPressed != kRightButton)
          {
            lifter_speed = 0;
          }
          motor[CrateLifterMotor] = lifter_speed;
        }
      }

      PlaySound(soundException);

      while(nNxtButtonPressed == kEnterButton)
      {}

      test_done = true;

      wait1Msec(200);

      break;

      //============================================
      // ball_elevator test
      //============================================

    case 4:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "elevator");
      nxtDisplayBigTextLine(5, "S1_C1_2");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      motor[ball_elevator] = 60;
      wait1Msec(2000);
      motor[ball_elevator] = 0;

      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(300);

      motor[ball_elevator] = -40;
      wait1Msec(500);
      motor[ball_elevator] = 0;

      wait1Msec(100);

      test_done = true;
      break;

      //============================================
      // right_servo test
      //============================================

    case 5:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "R_Servo");
      nxtDisplayBigTextLine(5, "S1_C3_1");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      servo[right_servo] = 0;
      wait1Msec(70);
      servo[left_servo] = 150;
      wait1Msec(700);
      servo[right_servo] = 85;
      wait1Msec(700);
      servo[right_servo] = 0;
      wait1Msec(700);
      servo[right_servo] = 180;
      wait1Msec(700);
      servo[left_servo] = 0;
      wait1Msec(100);

      test_done = true;
      break;

      //============================================
      // left_servo test
      //============================================

    case 6:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "L_Servo");
      nxtDisplayBigTextLine(5, "S1_C3_2");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      servo[left_servo] = 150;
      wait1Msec(700);
      servo[left_servo] = 85;
      wait1Msec(700);
      servo[left_servo] = 150;
      wait1Msec(700);
      servo[left_servo] = 0;
      wait1Msec(100);

      test_done = true;
      break;

      //============================================
      // left_servo & right_servo test
      //============================================

    case 7:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "R&LServo");
      nxtDisplayBigTextLine(5, "S1C3_1&2");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(500);

      servo[right_servo] = 0;
      wait1Msec(70);
      servo[left_servo] = 150;

      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(500);

      servo[right_servo] = 85;
      wait1Msec(70);
      servo[left_servo] = 85;

      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(500);

      servo[right_servo] = 180;
      wait1Msec(70);
      servo[left_servo] = 0;

      wait1Msec(100);

      test_done = true;
      break;

      //============================================
      // ball_hoop test
      //============================================

    case 8:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "BallHoop");
      nxtDisplayBigTextLine(5, "S1_C3_1");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      servoChangeRate[ball_hoop] = 2;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      servo[ball_hoop] = 0;

      wait1Msec(800);

      PlaySound(soundBeepBeep);

      servo[ball_hoop] = 130;

      wait1Msec(1500);

      PlaySound(soundBeepBeep);

      servo[ball_hoop] = 0;

      wait1Msec(1500);

      PlaySound(soundBeepBeep);

      servo[ball_hoop] = 130;

      wait1Msec(1500);

      PlaySound(soundBeepBeep);

      servo[ball_hoop] = 0;

      wait1Msec(500);

      test_done = true;

      break;

      //============================================
      // left_motor test
      //============================================

    case 9:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "L_Motor");
      nxtDisplayBigTextLine(5, "S1_C2_1");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      nMotorEncoder[left_motor] = 0;

      eraseDisplay();

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      motor[left_motor] = 60;
      wait1Msec(1500);
      motor[left_motor] = 0;

      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(500);

      motor[left_motor] = -60;
      wait1Msec(1500);
      motor[left_motor] = 0;

      wait1Msec(100);

      test_done = true;

      nMotorEncoder[left_motor] = 0;

      break;

      //============================================
      // right_motor test
      //============================================

    case 10:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "R_motor");
      nxtDisplayBigTextLine(5, "S1_C2_2");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      nMotorEncoder[right_motor] = 0;

      eraseDisplay();

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      motor[right_motor] = -60;
      wait1Msec(1500);
      motor[right_motor] = 0;

      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(500);

      motor[right_motor] = 60;
      wait1Msec(1500);
      motor[right_motor] = 0;

      wait1Msec(100);

      test_done = true;

      nMotorEncoder[right_motor] = 0;

      break;

      //============================================
      // left_motor & right_motor test
      //============================================

    case 11:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "R&LMotor");
      nxtDisplayBigTextLine(5, "S1C2_1&2");

      motors_off = mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      test_done = false;

      eraseDisplay();

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);

      beep();

      motor[left_motor] = 60;
      motor[right_motor] = -60;
      wait1Msec(1500);
      motor[left_motor] = 0;
      motor[right_motor] = 0;

      wait1Msec(300);
      PlaySound(soundBeepBeep);
      wait1Msec(500);

      motor[left_motor] = -60;
      motor[right_motor] = 60;
      wait1Msec(1500);
      motor[left_motor] = 0;
      motor[right_motor] = 0;

      wait1Msec(100);

      test_done = true;

      eraseDisplay();

      nMotorEncoder[left_motor] = 0;
      nMotorEncoder[right_motor] = 0;

      break;
      //======================================
      // sensors
      //======================================
    case 12:

      eraseDisplay();

      nxtDisplayBigTextLine(3, "sensors");

      motors_off = mON;
      test_done = false;

      while(nNxtButtonPressed != kEnterButton && nNxtButtonPressed != kLeftButton && nNxtButtonPressed != kRightButton)
      {}

      test_done = true;

      eraseDisplay();

      wait1Msec(800);
      //==============
      break;

    case 13:
      eraseDisplay();
      nxtDisplayBigTextLine(3, "BallLift");
      motors_off = mON;
      while(nNxtButtonPressed != kEnterButton){}
      while(nNxtButtonPressed == kEnterButton){}
      PlaySound(soundException);
      wait1Msec(800);
      PlaySoundFile("Watch Out.rso");
      wait1Msec(800);
      beep();
      test_done = false;
      while(nNxtButtonPressed != kEnterButton)
      {
        if(nNxtButtonPressed == kLeftButton && nNxtButtonPressed != kRightButton)
        {
          motor[ball_elevator] = 60;
          motor[motorC] = 60;
        }
        if(nNxtButtonPressed == kRightButton && nNxtButtonPressed != kLeftButton) motor[ball_elevator] = -40;
        if(nNxtButtonPressed != kRightButton && nNxtButtonPressed != kLeftButton)
        {
          motor[ball_elevator] = 0;
          motor[motorC] = 0;
        }
      }
      test_done = true;

      eraseDisplay();
      wait1Msec(800);
      //==============
      break;

      //======================================================
      // manual R&L servo
      //======================================================
    case 14:

      eraseDisplay();

      nxtDisplayBigTextLine(1, "Manaul");
      nxtDisplayBigTextLine(3, "R&LSrv");
      nxtDisplayBigTextLine(5, "S1C3_1&2");

      motors_off =mON;

      while(nNxtButtonPressed != kEnterButton)
      {}

      eraseDisplay();

      while(nNxtButtonPressed == kEnterButton)
      {}

      test_done = false;

      PlaySound(soundException);

      wait1Msec(800);

      PlaySoundFile("Watch Out.rso");

      wait1Msec(800);
      servo[right_servo] = 180;
      wait1Msec(70);
      servo[left_servo] = 0;

      ubyte leftServoMan = 0;
      ubyte rightServoMan = 180;

      wait1Msec(200);

      while(nNxtButtonPressed != kEnterButton)
      {
        if(nNxtButtonPressed == kLeftButton)
        {
          leftServoMan = leftServoMan+5;
          rightServoMan = rightServoMan-5;
          wait1Msec(150);
          if(leftServoMan > 220) leftServoMan = 220;
          if(rightServoMan > 18) rightServoMan = 0;
        }
        if(nNxtButtonPressed == kRightButton)
        {
          rightServoMan = rightServoMan+5;
          leftServoMan = leftServoMan-5;
          wait1Msec(150);
          if(leftServoMan > 220) leftServoMan = 0;
          if(rightServoMan > 220) rightServoMan = 220;
        }
        servo[right_servo] = rightServoMan;
        servo[left_servo] = leftServoMan;
        nxtDisplayBigTextLine(1, "%3d", leftServoMan);
        nxtDisplayBigTextLine(3, "%3d", rightServoMan);
      }

      PlaySound(soundException);

      while(nNxtButtonPressed == kEnterButton)
      {}

      test_done = true;

      wait1Msec(200);

      break;
    }
  }
}

task main()
{

  disableDiagnosticsDisplay();
  //--------------------------
  StartTask(smoke_test);

  StartTask(stop_all);
  //--------------------------

  test_done = true;

  SmokeTest = 1;

  PlaySoundFile("Hello.rso");

  //---------------------------------------

  StopTask(smoke_test);

  StopTask(stop_all);

  StartTask(smoke_test);

  StartTask(stop_all);

  while(true)
  {
    if (nNxtButtonPressed == kRightButton)
    {
      PlaySoundFile("! Click.rso");
      StopTask(smoke_test);
      StopTask(stop_all);
      SmokeTest = SmokeTest+1;
      StartTask(smoke_test);
      StartTask(stop_all);
      wait1Msec(400);
    }
    if (nNxtButtonPressed == kLeftButton)
    {
      PlaySoundFile("! Click.rso");
      StopTask(smoke_test);
      StopTask(stop_all);
      SmokeTest = SmokeTest-1;
      StartTask(smoke_test);
      StartTask(stop_all);
      wait1Msec(400);
    }
    while(test_done == false)
    {
      if(TSreadState(LifterEndStop) == true) Lifter_Pressed = true;
      else Lifter_Pressed = false;

      if(oldLifterPressed != Lifter_Pressed)
      {
        eraseDisplay();
        oldLifterPressed = Lifter_Pressed;
      }

      if(TSreadState(LifterHalfStop) == true) LifterH_Pressed = true;
      else LifterH_Pressed = false;

      if(oldLifterHPressed != LifterH_Pressed)
      {
        eraseDisplay();
        oldLifterHPressed = LifterH_Pressed;
      }

      if(SmokeTest == 1)
      {
        nxtDisplayBigTextLine(3, "%2d", nMotorEncoder[motorC]);
        Motor_Cvalue = nMotorEncoder[motorC];
      }
      if(SmokeTest == 2)
      {
        nxtDisplayBigTextLine(3, "%2d", nMotorEncoder[CrateLifterMotor]);
      }
      if(SmokeTest == 3)
      {
        nxtDisplayBigTextLine(2, "%2d", nMotorEncoder[CrateLifterMotor]);
        if(Lifter_Pressed == true) nxtDisplayBigTextLine(4, "LES:true");
        if(Lifter_Pressed != true) nxtDisplayBigTextLine(4, "LES:false");
        if(LifterH_Pressed == true) nxtDisplayBigTextLine(6, "LHS:true");
        if(LifterH_Pressed != true) nxtDisplayBigTextLine(6, "LHS:false");
      }
      if(SmokeTest == 9)
      {
        nxtDisplayBigTextLine(3, "%2d", nMotorEncoder[left_motor]);
      }
      if(SmokeTest == 10)
      {
        nxtDisplayBigTextLine(3, "%2d", nMotorEncoder[right_motor]);
      }
      if(SmokeTest == 11)
      {
        nxtDisplayBigTextLine(3, "R %2d", nMotorEncoder[right_motor]);
        nxtDisplayBigTextLine(5, "L %2d", nMotorEncoder[left_motor]);
      }
      if(SmokeTest == 12)
      {
        bearingDC = HTIRS2readDCDir(HTIRS2);
        bearingAC = HTIRS2readACDir(HTIRS2);
        int gyroValue = HTGYROreadRot(HTGYRO);
        nxtDisplayBigTextLine(2, "GY:%3d", gyroValue);
        nxtDisplayBigTextLine(4, "%3d,%3d", bearingAC,bearingDC);
        nxtDisplayBigTextLine(6, "AC   DC");
        wait1Msec(20);
      }
    }
    if (SmokeTest < 1)
    {
      SmokeTest = 14;
    }
    if (SmokeTest > 14)
    {
      SmokeTest = 1;
    }
  }
}
