#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    shoulder,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

#include "drivers/hitechnic-sensormux.h"
#include "drivers/common.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/hitechnic-magfield.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/lego-touch.h"

int s = 60;
int e = 60;
int w = 60;
bool locked = false;

task main()
{
	disableDiagnosticsDisplay();

	//servoChangeRate[wrist] = 1;
	servoChangeRate[elbow] = 3;
	servoChangeRate[shoulder] = 3;

	while(true)
	{
		getJoystickSettings(joystick);

		nxtDisplayBigTextLine(2, "S: %3d", s);
		nxtDisplayBigTextLine(4, "E: %3d", e);
		nxtDisplayBigTextLine(6, "W: %3d", w);

		if(w > 255) w = 255;
		if(e > 255) e = 255;
		if(s > 255) s = 255;
		if(w < 0) w = 0;
		if(e < 0) e = 0;
		if(s < 0) s = 0;

		if(abs(joystick.joy1_x1) > 20)
		{
			if(joystick.joy1_x1 > 0) w = w + 10;
			else w = w - 10;
			wait1Msec(50);
		}
		if(abs(joystick.joy1_y1) > 20)
		{
			if(joystick.joy1_y1 > 0) e = e + 5;
			else e = e - 5;
			wait1Msec(5);
		}
		if(abs(joystick.joy1_x2) > 20)
		{
			if(joystick.joy1_x2 > 0) s = s + 5;
			else s = s - 5;
			wait1Msec(5);
		}
		if(joy1Btn(1)) locked = true;
		if(joy1Btn(2)) locked = false;
		if(locked == false)
		{
			servo[elbow] = (((joystick.joy1_y1+127)/2)*255)/127;
			servo[wrist] = w;
			servo[shoulder] = (((joystick.joy1_x2+127)/2)*255)/127;
		}
	}
}
