#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR_MUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     GYRO_MUX,       sensorI2CCustom)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          lightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LF_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RF_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LR_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RR_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lifterMotor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     lifterMotor2,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    left_servo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    shoulder,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    lightServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    right_servo,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

#include "drivers/common.h"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/hitechnic-magfield.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/lego-touch.h"
#include "drivers/lego-light.h"
#include "drivers/lego-ultrasound.h"

const int LIFTER_SPEED_UP = 100;

#define WRIST_CLOSED 245
#define WRIST_OPEN 130
#define SHOULDER_DOWN 255
#define SHOULDER_UP 0
#define RIGHT_GRIPPER_START 50
#define RIGHT_GRIPPER_MID 140
#define RIGHT_GRIPPER_UP 240
#define LEFT_GRIPPER_START 180
#define LEFT_GRIPPER_MID 90
#define LEFT_GRIPPER_UP 0

#define mainScreen 1
#define driveForwardManual 2
#define driveSideManual 3
#define ringLiftManual 4
#define grabersManual 5
#define grabersAdjust 6
#define lightSensorMotor 7
#define LFmotor 8
#define RFmotor 9
#define LRmotor 10
#define RRmotor 11
#define shoulderManual 12
#define wristManual 13
#define sensorsView 14
#define extraServo 15
#define demo 16

#define grippersDown 0
#define grippersMed 1
#define grippersUp 2

task main()
{
	motor(lifterMotor)= -LIFTER_SPEED_UP;
	motor(lifterMotor2)= -LIFTER_SPEED_UP;
	wait1Msec(4000);
	motor(lifterMotor)= 0;
	motor(lifterMotor2)= 0;
	servo[right_servo] = RIGHT_GRIPPER_UP;
	servo[left_servo] = LEFT_GRIPPER_UP;
	wait1Msec(2000);
	servo[shoulder] = SHOULDER_UP;
	wait1Msec(2000);
	servo[wrist] = WRIST_OPEN;
	wait1Msec(4000);
	servo[shoulder] = SHOULDER_DOWN;
	wait1Msec(2000);
	servo[wrist] = WRIST_CLOSED;

	while(true)
	{}
}
