#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LF_motor,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RF_motor,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LB_motor,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RB_motor,      tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
  disableDiagnosticsDisplay();
  while(true)
  {
    getjoysticksettings();

  }
}
