#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left_motor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right_motor,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

int driveSpeed1;
int driveSpeed2;

task arm()
{
	while(true)
	{
		if(joy1Btn(6)) motor[motorA] = 100;
		if(joy1Btn(8)) motor[motorA] = -100;
		if(joy1Btn(6) != true && joy1Btn(8) != true) motor[motorA] = 1;
	}
}

task main()
{
	StartTask(arm);
	while(true)
	{
		if(joy1Btn(5) || joy1Btn(6))
		{
			driveSpeed1 = joystick.joy1_y1;
			driveSpeed2 = joystick.joy1_y2;
		}
		else
		{
			driveSpeed1 = (joystick.joy1_y1/5)*3;
			driveSpeed2 = (joystick.joy1_y2/5)*3;
		}

		if(abs(joystick.joy1_y1) > 10) motor[left_motor] = driveSpeed1;
		else motor[left_motor] = 0;
		if(abs(joystick.joy1_y2) > 10) motor[right_motor] = driveSpeed2;
		else motor[right_motor] = 0;
	}
}
