#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
#pragma config(Motor,  motorA,          lightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LF_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RF_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LB_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RB_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lifterMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    left_servo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    shoulder,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    right_servo,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

#include "drivers/hitechnic-sensormux.h"
#include "drivers/common.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/hitechnic-magfield.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/lego-touch.h"
#include "drivers/lego-ultrasound.h"
#include "drivers/lego-light.h"

const tMUXSensor LEGOUS = msensor_S3_4;//was 3
const tMUXSensor LEGOUS2 = msensor_S4_4;
const tMUXSensor LEGOLS = msensor_S3_2;

int num = 0;
int num2 = 0;
int sonarLive = 0;
int sonarLive2 = 0;

int nrm = 0;
//==================================================
// task to handle the sensors, mainly the SensorMux
//==================================================

task sensors()
{
	while(true)
	{
		//-------------------------
		// Sonar
		//-------------------------
		num = USreadDist(LEGOUS);
		num2 = USreadDist(LEGOUS2);
		if(num != 255) sonarLive = num;
		if(num2 != 255) sonarLive2 = num2;
	}
}

//====================================================
// Display
//====================================================
task display()
{
	while(true)
	{
		nxtDisplayBigTextLine(4, "%3d,%3d", num,num2);
	}
}

task main()
{
	//StartTask(sensors);
	//StartTask(display);
	disableDiagnosticsDisplay();
	while(true)
	{
	LSsetActive(LEGOLS);
		//-------------------------
		// Sonar
		//-------------------------
		num = USreadDist(LEGOUS);
		num2 = USreadDist(LEGOUS2);
		if(num != 255) sonarLive = num;
		if(num2 != 255) sonarLive2 = num2;

		//-------------------------
		// light
		//-------------------------
		LSsetActive(LEGOLS);
		nrm = LSvalNorm(LEGOLS);


		nxtDisplayBigTextLine(4, "%3d,%3d", num,num2);
		nxtDisplayBigTextLine(6, "L :%3d", nrm);

	}
}
