#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     COLOR,          sensorCOLORFULL)
#pragma config(Motor,  motorA,          IRmotor,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     CrateLifterMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ball_elevator, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     left_motor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     right_motor,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    ball_hoop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    right_servo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    left_servo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

#include "drivers/hitechnic-sensormux.h"
#include "drivers/common.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/hitechnic-magfield.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/lego-touch.h"

int joy1Btn1 = 0;
int servoNum = 0;
int servoNum2 = 0;
int state = 0;
bool rightTrue = false;
bool leftTrue = false;

task display()
{
	while(true)
	{
		nxtDisplayBigTextLine(5, "%2d", servoNum);
	}
}

task selector()
{
	while(true)
	{
		state = 0;
		while((nNxtButtonPressed != kEnterButton))
		{
			if(nNxtButtonPressed == kRightButton)
			{
				servoNum++;
				PlaySound(soundBlip);
			}
			while(nNxtButtonPressed == kRightButton)
			{}
			if(nNxtButtonPressed == kLeftButton)
			{
				servoNum--;
				PlaySound(soundBlip);
			}
			while(nNxtButtonPressed == kLeftButton)
			{}
		}
		PlaySound(soundException);
		while((nNxtButtonPressed == kEnterButton))
		{}
		state = 1;
		while((nNxtButtonPressed != kEnterButton))
		{
			if(nNxtButtonPressed == kRightButton)
			{
				rightTrue = true;
				leftTrue = false;
				PlaySound(soundBlip);
			}
			while(nNxtButtonPressed == kRightButton)
			{}
			if(nNxtButtonPressed == kLeftButton)
			{
				rightTrue = false;
				leftTrue = true;
				PlaySound(soundBlip);
			}
			while(nNxtButtonPressed == kLeftButton)
			{}
		}
		PlaySound(soundException);
		while(nNxtButtonPressed == kEnterButton)
		{}
	}
}

task main()
{
	StartTask(selector);
	StartTask(display);

	while(true)
	{
		if(servoNum > 5) servoNum2 = 5;
		if(servoNum < 0) servoNum2 = 0;
		switch(state)
		{
		case 0:

			rightTrue = false;
			leftTrue = false;

			break;

		case 1:

			if(rightTrue)
			{
				servo[servoNum] = 180;
			}
			if(leftTrue)
			{
				servo[servoNum] = 60;
			}
			break;
		}
	}
}
/*
joy1Btn1 = joy1Btn(1);
if(joy1Btn(1))
{
PlayTone(200,10);
servo[servo4] = 60;
servo[servo5] = 60;
}
if(joy1Btn(2))
{
PlayTone(400,10);
servo[servo4]= 180;
servo[servo5]= 180;
}
nxtDisplayBigTextLine(2, "%3d", joy1Btn1);
/***********************************/
//}
