#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     right_motor,   tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     left_motor,    tmotorNormal, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    right_servo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    left_servo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    test_servo,           tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define open 1
#define closed 2

#define no_Btn 1
#define full_speed 2
#define slow_speed 3

//---------------------------
int claw;
//---------------------------

#include "JoystickDriver.c"

//=============================
// servos/claw task
//=============================
task _claw()
{
	while(true)
	{
		switch (claw)
		{
		case open:
			// open servo positions
			servo[left_servo] = 225;
			servo[right_servo] = 35;
			break;
		case closed:
			// closed servo positions
			servo[left_servo] = 250;
			servo[right_servo] = 10;
			break;
		}
	}
}

int j1 = 0;
int j2 = 0;

int speed1;
int speed2;

int speed_selection = no_Btn;
//==========================
// task main
//==========================
task main()
{
	StartTask(_claw);

	servoChangeRate[right_servo] = 2;
	servoChangeRate[left_servo] = 2;

	waitForStart();

	while(true)
	{
		getJoystickSettings(joystick);

		//=========================================
		// drive motors
		//=========================================
		int j1 = joystick.joy1_y1;
		int j2 = joystick.joy1_y2;

		if(abs(j1)<20)   j1 = 0;

		if(abs(j2)<20)   j2 = 0;

		speed1 = (j1*100)/127;
		speed2 = (j2*100)/127;

		if ((joy1Btn(6)) || (joy1Btn(5))) speed_selection=full_speed;
		if ((joy1Btn(8)) || (joy1Btn(7))) speed_selection=slow_speed;

		switch(speed_selection)
		{

		case no_Btn:
			speed1=(speed1*45)/100;
			speed2=(speed2*45)/100;
			break;

		case full_speed: break;

		case slow_speed:
			speed1=speed1/5;
			speed2=speed2/5;
			break;
		}

		//motor[left_motor] = speed2;
		//motor[right_motor] = speed1;

		//===========================================
		// claw servos
		//===========================================
		if(joy1Btn(1))
		{
			claw = open;
		}
		if(joy1Btn(3))
		{
			claw = closed;
		}
		if(joy1Btn(5) == true && joy1Btn(7) == false)
		{
			servo[test_servo] = 200;
		}
		if(joy1Btn(7) == true && joy1Btn(5) == false)
		{
			servo[test_servo] = 55;
		}
		if(joy1Btn(5) == false && joy1Btn(7) == false)
		{
			servo[test_servo] = 127;
		}
	}
}
