#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorI2CCustom)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     right_motor,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     left_motor,    tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define encoder_drive 0
#define time_drive 1

#include "JoystickDriver.c"
#include "lib/xander/hitechnic-irseeker-v2.h"

const string LogFileName = "DATALOG.txt";
TFileIOResult LogIoResult;
TFileHandle LogFileHandle;
long LogFileSize = 36000;
string sString;
string CRLF = (char)13+(char)10;

int IR_value = SensorValue(IR);
int sonar_value = SensorValue(sonar);

#include "lib/abs_dlog.h"

task sensors()
{
	while(true)
	{
		IR_value = HTIRS2readACDir(IR);
		sonar_value = SensorValue(sonar);
	}
}

void drive(int speed,int dist,int drive_type,int samples)
{
	motor[right_motor] = speed;
	motor[left_motor] = speed;

	for(int i=0;i<samples;i++)
	{
		if(drive_type==1)
		{
			time1[T1] = 0;
			while(time1[T1]<(dist/samples)){}
		}
		else
		{
			nMotorEncoder[left_motor] = 0;
			while(abs(nMotorEncoder[left_motor])<(dist/samples)){}
		}
		abs_dlog(__FILE__ ,"","sample",i+1);
	}
	motor[right_motor] = 0;
	motor[left_motor] = 0;
}

task main()
{
	StartTask(sensors);

	Delete(LogFileName, LogIoResult);
	OpenWrite(LogFileHandle, LogIoResult, LogFileName, LogFileSize);

	abs_dlog(__FILE__ ,"start","test",nPgmTime);

	for(int i=0;i<10;i++)
	{
		abs_dlog(__FILE__ ,"","test#",i+1);

		drive(70,14100,encoder_drive,12);

		while(nNxtButtonPressed != kEnterButton){}
		while(nNxtButtonPressed == kEnterButton){}
		abs_dlog(__FILE__ ,"NEXT SET","");
	}
	abs_dlog(__FILE__ ,"program","end");
	Close(LogFileHandle, LogIoResult);
}
