#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     GYRO_MUX,       sensorI2CCustom)
#pragma config(Sensor, S3,     SENSOR_MUX,     sensorI2CCustom)
#pragma config(Sensor, S4,     ANGLE_SENSOR,   sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     right_motor,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     left_motor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     flag_motor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lifter_motor,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    right_servo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    left_servo,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//-----------------------
// sensor/mux/joystick includes
//-----------------------

#include "joystickdriver.c"
#include "lib/xander/hitechnic-sensormux.h"
#include "lib/xander/hitechnic-irseeker-v2.h"
#include "lib/xander/hitechnic-gyro.h"
#include "lib/xander/hitechnic-angle.h"
#include "lib/xander/hitechnic-accelerometer.h"

//-----------------------
// custom functions includes
//-----------------------

#include "lib/global_varaibles.h"
#include "lib/abs_screen.h"
#include "lib/math_utils.h"
#include "lib/abs_sensors.h"
#include "lib/abs_smoke_execute.h"


//==================================
// main program
//==================================
task main()
{
	StartTask(screen);
	StartTask(abs_sensors_read);
	while(true)
	{
		while(nNxtButtonPressed == kEnterButton){}
		screen_state = s_smoke_test;
		//---------------------------------------
		// Start of mission selection
		//---------------------------------------

		while(nNxtButtonPressed != kEnterButton)
		{
			if(nNxtButtonPressed == kRightButton)
			{
				PlaySoundFile("! Click.rso");
				while(nNxtButtonPressed == kRightButton){}
				if(smoke_test_num < smoke_test_total) smoke_test_num++;
				else smoke_test_num = smoke_test_total;
			}
			if(nNxtButtonPressed == kLeftButton)
			{
				PlaySoundFile("! Click.rso");
				while(nNxtButtonPressed == kLeftButton){}
				if(smoke_test_num > 1) smoke_test_num--;
				else smoke_test_num = 1;
			}
		}
		PlaySoundFile("! Click.rso");
		while(nNxtButtonPressed == kEnterButton){}
		eraseDisplay();

		abs_smoke_execute();
	}
}
