#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,         sensorAnalogActive)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right_motor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left_motor,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 *
 *  @file tele_op.c
 *
 *  @brief The tele_op program for the robot
 *
 *  @copyright Copyright 2013, Got Robot? FTC Team 5037
 *
 */

 /*Includes*/

#include "JoystickDriver.c"
//========================================
// Main program
//========================================

task main ()
{

}
